version: '3.9'
services:
  gitlab:
    image: gitlab/gitlab-ce:18.2.8-ce.0
    hostname: gitlab.docker.internal
    # ports:
      # - '80:80'
      # - '8443:443'
      # - '8822:22'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        from_file('/opt/omnibus_config/gitlab.rb')
    # configs:
    #   - source: gitlab
    #     target: /omnibus_config.rb
    labels:
      - 'traefik.http.routers.gitlab.tls=true'
      - 'traefik.http.routers.gitlab.rule=Host(`gitlab.$MY_DOMAIN`)'
      - 'traefik.http.routers.gitlab.entrypoints=websecure'
      - 'traefik.http.services.gitlab.loadbalancer.server.port=80'
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-data:/var/opt/gitlab
      - ./config:/opt/omnibus_config:ro
  runner:
    image: gitlab/gitlab-runner:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - gitlab-runner:/etc/gitlab-runner
      - gitlab-ssh:/root/.ssh

volumes:
  gitlab-config: {}
  gitlab-data: {}
  gitlab-runner: {}
  gitlab-ssh: {}

# configs:
#   gitlab:
#     file: ./gitlab.rb
